### ISSUE TITLE
Duplicating Pinned Tabs

### ISSUE THREAD

**Issue by jeaninem71** [scottwio/forever-pinned#2]
The extension keeps duplicating the tabs that I have it set to.  I keep closing the duplicates and look again and there are more.  Anyone else have this issue? Is there an easy fix by editing the code or will you need to work on it?

**Comment by scottwio** [comment]
Do you mind letting me know what URLs you have set to pin.

**Comment by jeaninem71** [comment]
It doesn't do it all the time.  Last night it was ok, but then I started new tabs to go to other sites and when I went back to my chrome window there were 4 of each pins, so it multiplied 3 times on its own.  Perhaps I had started 3 new tabs. I cant duplicate it so I cant tell you if it's happening when the window is minimized or what's causing it.  I just opened 3 new tabs and surfed around and closed them but the pins didn't duplicate.  I havent seen it do it in front of me with the window open, so that makes me think it's happening when I have it minimized.  If I notice anything specific I will let you know.

http://uet.vnu.edu.vn/~chauttm/e-books/java/Head-First-Java-2nd-edition.pdf
http://www.tutorialspoint.com/java/index.htm
http://hilite.me
http://www.udemy.com

**Comment by jeaninem71** [comment]
I forgot to mention that I do have other pins with your extension, just pinned by right clicking and selecting pin tab.  However, the damn pins never stayed, hence the reason I downloaded your extension.  These aren't pins I keep up all the time, so I didn't want to put them into the extension and have to remove them again.  The ones that I pinned without your extension are not duplicating.  I hope this leads you in the right direction.

**Comment by scottwio** [comment]
I just posted a new version to the chrome store 0.27 hopefully this should fix the issues you were seeing. The duplication search should be improved. It might take a bit of time for the new version to show up on the chrome store but when it does give it a whirl.

**Comment by jeaninem71** [comment]
Thank you for your help.  I havent installed it yet, but it did just happen again.  I think it was whenever I opened my history up. Maybe it's being triggered with the chrome://  browser windows?

**Comment by jeaninem71** [comment]
Unfortunately it is still duplicating the tabs, let me know if you update it again. for now I'm just going to disable it.

**Comment by spdy** [comment]
What's happening is that (I think) Chrome is keeping track of the pinned tab when you close it.
So when you open it, Chrome reopen the last pinned tab, and the extension open the pin tab that you wanted to be open.
It can be replicated easily on Chrome (I'm on OSX 10.9.5), open a window, let the pinned tab loads, close it normally, then reopen Chrome, it'll add all the pinned tab added in the extension.
I don't know if it's possible but there are 2 solutions:
- When Chrome starts, close all open pinned tabs, then reopen the one from the extension.
- When Chrome starts, check what pinned tab are already opened and make a list of non opened pinned tabs, then add these non-opened pinned tabs to the current window.

**Comment by sstent** [comment]
Still seeing this issue on multiple machines

**Comment by danielbullon** [comment]
+1 on this issue, running Chrome 54.0.2840.71 (64-bit) on Mac OS

**Comment by codazoda** [comment]
Same problem for me. I have Chrome settings set to open a new tab (so it doesn't open the last tabs I was using). If I open a new window or close the current window it works as expected. If, however, I quite Chrome completely and open a new window, two pinned windows open.

If this is a problem with Chrome opening tabs, maybe a quick workaround would be to wait for a few seconds before looking at existing tabs to see if the tab we plan to pin is already open. Perhaps it takes a second for the tab to load and/or show up in the API call, so it looks like it's not open so the extension tries to open it. All this is conjecture and I haven't looked at the source yet (but I may).

**Comment by troyf** [comment]
> Duplicating Pinned Tabs [at startup]
In chrome settings, there is ON_STARTUP/CONTINUE_WHERE_YOU_LEFT_OFF... That may be happening here, the existing pins & pages are restored by chrome, then those configured in FOREVER-PINNED are 'restored'.

My resolution, if the information is available to the plug-in, would be to look at only the domain names. Prior to opening a domain from the plug-in, check the existing pinned domains to see if it already exists. When checking look only at domain.tld for the listed. Ignore subdomain if there is a subdomain.domain.tld. Maybe create a configuration that controls this 'dedup' behavior.

Troy.
#

**Comment by rogergithubbing** [comment]
Hello,
It happens to me too, it keeps duplicating the tabs if I close the browser with the already pinned tabs not closed. If I close the browser with no pinned tabs, it does not repeat.

Do you plan to fix this issue in a nearby future ?

Thanks,

Roger

**Comment by DanielArnett** [comment]
I just submitted a pull request for a fix. In the mean time while @scottwio is reviewing it you can install the [fixed version from my source here](https://github.com/DanielArnett/forever-pinned).

[Here's some info on how to install an extension from source.](https://stackoverflow.com/a/49769909/2116716) Hopefully this works on Windows too.

**Comment by rogergithubbing** [comment]
Thanks a lot !!! I will try it asap. Good work !

**Comment by scottwio** [comment]
Thanks @DanielArnett you fix is in 0.29
