### ISSUE TITLE
"Ignore URL parameters" option doesn't go far enough

### ISSUE THREAD

**Issue by devuxer** [scottwio/forever-pinned#5]
The option "ignore url parameters when comparing opened and saved tabs" doesn't go far enough. I still end up with duplicate pinned tabs for things like Gmail, Google Calendar, and Google Keep This is because, when you open a particular item (like an email in Gmail), the main part of the URL changes, not just the query parameters.

What's needed is to support a wildcard.

So, if I enter `https://mail.google.com/*`, it will match both of these URLs:

- https://mail.google.com/mail/u/0/#inbox
- https://mail.google.com/mail/u/0/#inbox/FMfcgxvxBjVKkljXbfSFXgmstfnQwRxD

**Comment by DanielArnett** [comment]
I felt the same so I made a version that does this, without needing the star or any regular expressions.
I just submitted a pull request for a fix. In the mean time while @scottwio is reviewing it you can install the [fixed version from my source here](https://github.com/DanielArnett/forever-pinned).

[Here's some info on how to install an extension from source.](https://stackoverflow.com/a/49769909/2116716) Hopefully this works on Windows too.

Using your example above you would only need to enter `https://mail.google.com/`, and any pinned tab from gmail would suffice.

**Comment by scottwio** [comment]
Merged and included in 0.29 thanks @DanielArnett

**Comment by DanielArnett** [comment]
@scottwio Thanks for integrating that so quickly. I feel like ignoreParams should be true by default. My pinned tabs are all gmail, slack, calendar; things which usually have a bunch of parameters, and it's annoying to have to close slack tabs every time I open chrome (hence me digging into it and submitting the pull request). Do you know how to set ignoreParams checkbox to true by default? I don't have much js experience. If that's not trivial then maybe we should change the label from "Ignore url parameters..." to something like "Always open this specific URL with exact parameters", and then set ignoreParams to be the opposite of the checkmark's value. Does this make sense? Do you think it should be a default value?

**Comment by scottwio** [comment]
Technically I would imagine that's pretty easy to do. However, I would be worried about changing the functionality in this way as it would mean that behaviour suddenly becomes different for long-time users.
